name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build_push:
    # uses Docker Setup Buildx
    # See: https://github.com/marketplace/actions/docker-setup-buildx#with-qemu
    name: Build and push Docker image to GitHub Packages

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io # GitHub Container Registry (GH Packages for Docker)
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      -
        name: Retrieve version tag
        # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
        # See https://stackoverflow.com/a/9533099/2427596
        # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      -
        name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Version in: ${{ GITHUB_REF#refs/tags/ }}
          # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
          # See https://stackoverflow.com/a/9533099/2427596
          tags: puppeteer-html2pdf:${{ GITHUB_REF#refs/tags/ }},ghcr.io/ccjmne/puppeteer-html2pdf:${{ GITHUB_REF#refs/tags/ }}
